# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557b4444f06db88cebce3d6beb00676ef2c956950830d3da39bff5882c7d1e84a63b6081f8009509ff0d249c6ba2567f844ab43ad663478d79f21b473521e3af

test:
  secret_key_base: f350e6081c610156c1991bb01b9a7155083255aa9c197dc6830b33a600f7b990a6324b5f8227fc73c4e4fdafe4e2a1683cfe6cabb0377e38adf115a6f361354f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
